# FROM node:latest as builder

# RUN mkdir -p /app

# WORKDIR /app

# COPY . .

# RUN npm install -g @angular/cli @angular-devkit/build-angular && npm install 
# # RUN npm run build --prod
# EXPOSE 4201

# CMD ["npm", "start"]

# FROM nginx:alpine
# COPY src/nginx/etc/conf.d/default.conf /etc/nginx/conf.d/default.conf
# COPY --from=builder app/dist/veterinary-clinic usr/share/nginx/html


